### ISSUE TITLE
[ISSUE]Recovery logic that occurred during the initial operation requires an exception case

### ISSUE THREAD

**Issue by hshs1103** [addb-swstarlab/LESS#2]
In the current version, the initial and subsequent triggered cases are covered in the data recovery process.

However, it did not address situations in which data recovery could not proceed.

I think that we need to deal with this exception.

**Comment by addb-swstarlab** [comment]
we have finished reflecting the exception case.
Please refer to the link below.

https://github.com/addb-swstarlab/LESS/commit/505e8f07ad3a19511d1c55cbc506c3bdb7063653
